{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "azure-keyvault-secret-reloader.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "azure-keyvault-secret-reloader.name" . }}
    helm.sh/chart: {{ include "azure-keyvault-secret-reloader.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
data:
  SP_CLIENT_ID: {{ required ".Values.servicePrincipal.clientId is required." .Values.servicePrincipal.clientId | b64enc | quote }}
  SP_CLIENT_SECRET: {{ required ".Values.servicePrincipal.clientSecret is required." .Values.servicePrincipal.clientSecret | b64enc  | quote }}
  SP_TENANT_ID: {{ required ".Values.servicePrincipal.tenant is required." .Values.servicePrincipal.tenant | b64enc | quote }}
{{- end }}