{{- if .Values.defaultCertificate.enabled }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "cluster-base.fullname" . }}-default-tls
  labels:
    app.kubernetes.io/name: {{ include "cluster-base.name" . }}
    helm.sh/chart: {{ include "cluster-base.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  # The name of the Kubernetes secret resource to store the signed TLS keypair
  secretName: {{ .Values.defaultCertificate.secretName }}
  # The Issuer to use for this certificate
  issuerRef:
    name: {{ .Values.defaultCertificate.issuer }}
    kind: {{ .Values.defaultCertificate.issuerKind }}
  # The common name (CN) for the TLS certificate
{{- if .Values.defaultCertificate.commonName }}
  commonName: {{ squote .Values.defaultCertificate.commonName }}
{{- end }}
  # A list of domains to include on the TLS certificate
  dnsNames:
  {{- range $key, $val := .Values.defaultCertificate.domains }}
  - {{ squote $val }}
  {{- end }}
{{- end }}
