version: 2
jobs:
  build:
    branches:
      only:
      - master
    docker:
    - image: alpine
    steps:
    - checkout
    - run:
        name: helm-github-pages
        environment:
        - GITHUB_PAGES_REPO: jahstreet/helm-charts
        - HELM_CHARTS_SOURCE: "livy jupyter-sparkmagic spark-cluster"
        command: wget -O - https://raw.githubusercontent.com/jahstreet/helm-github-pages/master/publish.sh | sh
