version: 2
jobs:
  build:
    branches:
      only:
      - /release-.*/
    docker:
    - image: alpine
    steps:
    - checkout
    - run:
        name: helm-github-pages
        environment:
        - GITHUB_PAGES_REPO: jahstreet/helm-charts
        - HELM_CHARTS_LIST: "cluster-base livy jupyter-sparkmagic spark-cluster spark-monitoring azure-keyvault-secret-reloader"
        command: wget -O - https://raw.githubusercontent.com/jahstreet/helm-github-pages/master/publish.sh | bash
