prometheusoperator:

  prometheus:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      paths:
      - /prometheus/?(.*)
      hosts:
      - my-cluster.example.com
      tls:
      - secretName: cluster-tls
        hosts:
        - my-cluster.example.com
    prometheusSpec:
      externalUrl: "https://my-cluster.example.com/prometheus/"

  grafana:
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        nginx.ingress.kubernetes.io/rewrite-target: /$1
      path: /grafana/?(.*)
      hosts:
      - my-cluster.example.com
      tls:
      - secretName: cluster-tls
        hosts:
        - my-cluster.example.com
    env:
      GF_SERVER_DOMAIN: "my-cluster.example.com"
      GF_SERVER_ROOT_URL: "https://my-cluster.example.com/grafana/"
