apiVersion: v1
kind: Secret
metadata:
  name: spark-defaults-conf-secret
type: Opaque
data:
  # History Server
  spark.hadoop.fs.defaultFS: "<base64-encoded-value>"
  spark.hadoop.fs.azure.sas.<your-blob-container-name>.<your-storage-account-name>.blob.core.windows.net: "<base64-encoded-value>"
  # ADL
  spark.hadoop.fs.adl.oauth2.client.id: "<base64-encoded-value>"
  spark.hadoop.fs.adl.oauth2.credential: "<base64-encoded-value>"
  spark.hadoop.fs.adl.oauth2.refresh.url: "<base64-encoded-value>"
  # ABFS
  spark.hadoop.fs.azure.account.oauth2.client.id: "<base64-encoded-value>"
  spark.hadoop.fs.azure.account.oauth2.client.secret: "<base64-encoded-value>"
  spark.hadoop.fs.azure.account.oauth2.client.endpoint: "<base64-encoded-value>"