apiVersion: v1
appVersion: 0.38.1
description: Cluster monitoring chart with Prometheus Operator, Prometheus Pushgateway and Loki
keywords:
- monitoring
- prometheus-operator
- prometheus
- grafana
- alertmanager
- pushgateway
- loki
maintainers:
- email: aliaksandr_sasnouskikh@epam.com
  name: Aliaksandr Sasnouskikh
name: spark-monitoring
version: 1.0.0
