apiVersion: v1
appVersion: "2.4.1"
description: A Helm chart for Spark cluster with Livy atop Kubernetes
keywords:
- livy
- spark
- jupyter
- history-server
maintainers:
- email: jahstreetlove@gmail.com
  name: Aliaksandr Sasnouskikh
name: spark-cluster
version: 0.1.0